Шаг 1
rdtabb/react-stellar-burger pull request #4
Opened 2023-11-28 22:26 UTC by rdtabb

- Раутинг
 - Авторизация
 - Рефакторинг на RTK Query
 - Рефакторинг файловой структуры

Наименование папок и компонентов кебаб-кейсом -- стандарт нейминга в моей компании, поэтому надеюсь на Ваше понимание

2023-11-29 03:45 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Хорошая работа.

### **Вы молодец!**

- Теперь у вас есть роутинг;
- Есть регистрация и авторизация;

### **Но есть несколько замечаний, которые нужно исправить:**

- <https://disk.yandex.com/i/kKlMDGyF9R1Gzg> - Проект не собирается, т.к. не совпадает регистр букв в названии файла и при импорте. Проверьте, что в системе контроля версий правильный регистр и при необходимости измените <https://noteskeeper.ru/heritage/672/>;

- Страница с конструктором должна быть доступна любому пользователю, а не только зарегистрированным.

- Страница `/ingredients/:id` должна быть доступна любому пользователю, а не только зарегистрированным.

- <https://disk.yandex.com/i/28EgU5BshjviTA> - у вас не должна выделяться ссылка, если пользователь не находиться на данной странице.

- <https://disk.yandex.com/i/zagBdl_4e9MIuQ> - Нужно поправить ссылки, они не должны быть белого цвета. А также иконка тоже должна быть белого цвета, если пользователь находиться на соответствующей странице.

- <https://disk.yandex.com/i/AYCruS0392FHlQ> - ссылка должны выделяться белым цветом, т.к. пользователь находиться на нужно странице.

- <https://disk.yandex.com/i/dguvAybbxWcy8A> - Нужно поправить `url` в соответствии с заданием, а также прижать контент к верху страницы, как показано на макете - <https://disk.yandex.com/i/n4HLU1IX0Obg2g>.

- <https://disk.yandex.com/i/4waOHg7P7MplAw> - по умолчанию поле должно быть пустым и иметь возможность редактировать значение. А также у вас не работает глазик.

- В директории `components` должен быть компонент App. Компонент `App`, он также должен быть в папке (как и другие компоненты). Как правило, это основной компонент в React, который выступает в качестве контейнера для всех остальных компонентов;

- Вы должны добавлять в хедер запроса `POST /orders`, токен пользователя `Bearer ...`, чтобы сервер понимал что заказ сделал зарегистрированный пользователь (время обработки заказа должно быть в разы больше, если вы всё правильно сделали);

- По чек-листу, требуется реализовать:

  - По клику на ингредиент <https://disk.yandex.com/i/LIJMbJy_r9ox6w>, у вас пользователь переходит на другую страницу. Как должно быть:

    При клике по ингредиенту происходит переход на маршрут /ingredients/:id и открывается модальное окно с описанием ингредиента. При прямом переходе на этот маршрут открывается страница с информацией об ингредиенте. Прошу обратить внимание на запрос `GET - /ingredients` (получение ингредиентов), его лучше делать всего 1 раз, в компоненте `app`;

  - Роуты `/login` и `/register`, `/forgot-password` и `/reset-password` недоступны авторизованным пользователям;

  - `/reset-password` доступен неавторизованным пользователям только после посещения маршрута `/forgot-password` и ввода адреса электронной почты для восстановления пароля;

  - При клике на «История заказов» происходит переход на экран `/profile/orders`, ссылка «История заказов» становится активной, экран `/profile/orders` пока отображается пустым;

  - Если пользователь отредактировал данные в форме, то появляются кнопки "Отмена" и "Сохранить".
    При нажатии кнопки "Сохранить" на странице профиля пользователя отправляется соответствующий запрос к Api содержащий измененные данные.
    При нажатии кнопки "Отмена" значения полей формы возвращаются в состояние до редактирования, а кнопки "Отмена" и "Сохранить" скрываются.

    <https://disk.yandex.com/i/I3Nti2X9vcnpnA>

  - Вам нужно проверить запросы, некоторые их них (`GET /auth/user`, `POST /order`, `PATCH /user`) должны посылать `accessToken`. При запросах использующих accessToken проверяется ответ сервера. Если время жизни токена истекло, то выполняется запрос обновления токена и повторяется запрос, который не был выполнен успешно.

### **Сделает код лучше:**

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-11-29 03:45 UTC, ArslanMustafin commented on src/App.tsx
> +            />
**Надо исправить:**

Страница должна быть доступна всем пользователям

2023-11-29 03:45 UTC, ArslanMustafin commented on src/App.tsx
> +            />
**Надо исправить:**

Страница должна быть доступна всем пользователям

2023-11-29 03:45 UTC, ArslanMustafin commented on src/components/Protected/Protected.tsx
> +  }, []);
**Надо исправить:**

Лучше перенести этот вызов в компонент `app`, чтобы он вызвался единожды при запуске приложения. А то вызовы по несколько раз, это не очень хорошо. https://disk.yandex.com/i/wlSt14gwIoaF4w

2023-11-29 03:45 UTC, ArslanMustafin commented on src/components/app-header/app-header.tsx
> +            <BurgerIcon type="primary" />
**Надо исправить:**

Здесь и далее.

Вы также должны менять стиль иконки, в зависимости от `isActive`

2023-11-29 03:45 UTC, ArslanMustafin commented on src/components/profile-page-components/components/form.tsx
> +      <div style={{ position: "relative", width: "fit-content" }}>
**Надо исправить:**

Здесь и далее.

Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданных классов. Лучше дать какой-то класс, и там указать уже нужные вам стили.

2023-11-29 03:45 UTC, ArslanMustafin commented on src/components/profile-page-components/components/form.tsx
> +      <PasswordInput value="********" onChange={() => {}} disabled />
**Надо исправить:**

по умолчанию значения быть не должно. А также нужно иметь возможность редактировать поле.

2023-11-29 03:45 UTC, ArslanMustafin commented on src/pages/ingredient-details/ingredient-details.tsx
> +    <div style={{ display: "grid", placeContent: "center", height: "100%" }}>
**Надо исправить:**

Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданных классов. Лучше дать какой-то класс, и там указать уже нужные вам стили.

2023-11-29 03:45 UTC, ArslanMustafin commented on src/pages/login-form/login-form.tsx
> +        navigate(ROUTES.CONSTRUCTOR);
**Надо исправить:**

не думаю что тут стоит делать `navigate`, вы уже делаете это в компоненте `protected`

2023-11-29 03:45 UTC, ArslanMustafin commented on src/pages/login-form/login-form.tsx
> +        navigate(ROUTES.CONSTRUCTOR);
**Надо исправить:**

не думаю что тут стоит делать `navigate`, вы уже делаете это в компоненте `protected`

2023-11-29 03:45 UTC, ArslanMustafin commented on src/services/api/apiSlice.ts
> +    }),
**Надо исправить:**

здесь и далее, где используется `access токен`.

Вам нужно обрабатывать ошибки запросов и при возникновении ошибки jwt expired и вызывать обновление токена при ошибке, а потом снова делать запрос.

Есть неплохой пример на офф. документации https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#automatic-re-authorization-by-extending-fetchbasequery

2023-12-03 06:20 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

### **Вы молодец!**

- многие замечания были исправлены;

### **Но всё ещё есть несколько замечаний, которые нужно исправить:**

- <https://disk.yandex.com/i/MlA-lRJ2VD78dQ> - Проект не собирается, т.к. не совпадает регистр букв в названии файла и при импорте. Проверьте, что в системе контроля версий правильный регистр и при необходимости измените <https://noteskeeper.ru/heritage/672/>. Для проверки нужно клонировать проект, и переключиться на ветку PR;

- <https://disk.yandex.com/i/_64BfPRNWLTtaw> - нужно запретить нажимать кнопку, если пользователь не выбрал булки.

-<https://disk.yandex.com/i/Sr6jo9k6aFFIog> - если открыть страницу `ingredient-details/:id` в новом вкладке, то у вас не отображается ингредиент. А также лучше поменять `url` `ingredient-details` на `ingredients`. Так будет более правильно, т.к. мы даём понять пользователю что выбрали какой-то определенный ингредиент из всех;

- <https://disk.yandex.com/i/28EgU5BshjviTA> - у вас не должна выделяться ссылка, если пользователь не находиться на данной странице.

- <https://disk.yandex.com/i/zagBdl_4e9MIuQ> - Нужно поправить ссылки, они не должны быть белого цвета. А также иконка тоже должна быть белого цвета, если пользователь находиться на соответствующей странице.

- <https://disk.yandex.com/i/AYCruS0392FHlQ> - ссылка должны выделяться белым цветом, т.к. пользователь находиться на нужно странице.

- <https://disk.yandex.com/i/4waOHg7P7MplAw> - поле должно иметь возможность редактировать значение.

- В директории `components` должен быть компонент App. Компонент `App`, он также должен быть в папке (как и другие компоненты). Как правило, это основной компонент в React, который выступает в качестве контейнера для всех остальных компонентов;

- Вы должны добавлять в хедер запроса `POST /orders`, токен пользователя `Bearer ...`, чтобы сервер понимал что заказ сделал зарегистрированный пользователь (время обработки заказа должно быть в разы больше, если вы всё правильно сделали);

- По чек-листу, требуется реализовать:

  - Роуты `/login` и `/register`, `/forgot-password` и `/reset-password` недоступны авторизованным пользователям.

  - Если пользователь отредактировал данные в форме, то появляются кнопки "Отмена" и "Сохранить".
    При нажатии кнопки "Сохранить" на странице профиля пользователя отправляется соответствующий запрос к Api содержащий измененные данные.
    При нажатии кнопки "Отмена" значения полей формы возвращаются в состояние до редактирования, а кнопки "Отмена" и "Сохранить" скрываются.

    <https://disk.yandex.com/i/I3Nti2X9vcnpnA>

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-12-03 06:20 UTC, ArslanMustafin commented on src/services/api/apiSlice.ts
> +  baseQuery: baseQueryWithReauth,
**Надо исправить:**

Лучше вынести отдельно запросы которым нужен `baseQueryWithReauth` и которым он не нужен.

Нужен только для этих запросов `GET /auth/user`, `POST /order`, `PATCH /user`.

2023-12-03 06:20 UTC, ArslanMustafin commented on src/components/app-header/app-header.tsx
> +            {/* Стиль иконки меняется, т.к. она наследует opacity от стилей tab и tab_active */}
**Надо исправить:**

Это всё отлично!) но есть не соответствие дизайну. Иконка всегда остаётся белого цвета, хоть и меняется opacity

2023-12-03 06:20 UTC, ArslanMustafin commented on src/components/form/components/form-container.tsx
> +};
**Надо исправить:**

не стоит выносить в отдельный компонент 1 элемент.

2023-12-03 06:20 UTC, ArslanMustafin commented on src/components/form/components/form-input.tsx
> +};
**Надо исправить:**

также, не стоит делать компонент для компонента, если вы не добавляется какой-то новый функционал.

2023-12-03 06:20 UTC, ArslanMustafin commented on src/components/form/components/form-inputs.tsx
> +});
**Надо исправить:**

И здесь тоже не нужен новый компонент)) Т.к. типы практически идентичные, и их можно просто вынести в отдельный файлик.

2023-12-03 06:20 UTC, ArslanMustafin commented on src/components/profile-page-components/components/form.tsx
> +      <PasswordInput value="" onChange={() => {}} disabled={true} />
**Надо исправить:**

Поле должно быть доступно для редактирования, иначе как пользователь будет менять свой пароль?)

2023-12-03 06:20 UTC, ArslanMustafin commented on src/pages/login-form/login-form.tsx
>          navigate(ROUTES.CONSTRUCTOR);
**Надо исправить:**

Думаю, это лучше исправить)) Если после логина у вас не происходит редиректа, значит это проблема компонента `protected`, нужно править его. Для примера вот рабочий вариант `protect-route` компонента.

```js
export const ProtectedRoute = ({ onlyUnAuth = false, children }) => {
  const isAuthChecked = useSelector((state) => state.user.isAuthChecked);
  const user = useSelector((state) => state.user.data);
  const location = useLocation();

  if (!isAuthChecked) {
    return <Preloader />;
  }

  if (onlyUnAuth && user) {
    const { from } = location.state || { from: { pathname: "/" } };
    return <Navigate to={from} />;
  }

  if (!onlyUnAuth && !user) {
    return (
      <Navigate
        to="/login"
        state={{ from: location }}
      />
    );
  }

  return children;
};

// использование

<Route
  path="/register"
  element={
    <ProtectedRoute onlyUnAuth={true}>
      <Register />
    </ProtectedRoute>
  }
/>

<Route
  path="/profile"
  element={
    <ProtectedRoute>
      <Profile />
    </ProtectedRoute>
  }
/>
```

`isAuthChecked` - это просто флаг, который показывает, выполнился ли запрос на получения пользователя или ещё нет. Важен сам процесс, если он завершён, то флаг будет `true` (не зависит от результат, т.к. он будет `true` в любом случае, даже если будет ошибка), если он ещё не произошёл, то будет `false`.

2023-12-03 06:20 UTC, ArslanMustafin commented on src/App.tsx
> +    store.dispatch(initAuthCheck());
**Надо исправить:**

Перенесите обёртку DnD и редакса в `index.js`. Обычно все обёртки используются именно там. Тогда вы можете спокойно уже тут использовать `useDispatch`.

2023-12-04 06:38 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

### **Вы молодец!**

- многие замечания были исправлены;

### **Но всё ещё есть несколько замечаний, которые нужно исправить:**

- <https://disk.yandex.com/i/MlA-lRJ2VD78dQ> - Проект не собирается, т.к. не совпадает регистр букв в названии файла и при импорте. Проверьте, что в системе контроля версий правильный регистр и при необходимости измените <https://noteskeeper.ru/heritage/672/>. Для проверки нужно клонировать проект, и переключиться на ветку PR;

-<https://disk.yandex.com/i/Sr6jo9k6aFFIog> - если открыть страницу `ingredients/:id` в новом вкладке, то у вас не отображается ингредиент.

- <https://disk.yandex.com/i/VIWHbmyaCmj7TQ> - ссылка не должна выделяться белым цветом, пользователь ведь на странице профиля.

- <https://disk.yandex.com/i/4waOHg7P7MplAw> - поле должно иметь возможность редактировать значение. При редактировании должны появляться кнопки (Отмена и Сохрнять), вообщем, такое же флоу что и для остальных полей. Просто мы это поле очищаем даже когда нажимаем на кнопку сохранить;

- В директории `components` должен быть компонент App. Компонент `App`, он также должен быть в папке (как и другие компоненты). Как правило, это основной компонент в React, который выступает в качестве контейнера для всех остальных компонентов;

- Вы должны добавлять в хедер запроса `POST /orders`, токен пользователя `Bearer ...`, чтобы сервер понимал что заказ сделал зарегистрированный пользователь (время обработки заказа должно быть в разы больше, если вы всё правильно сделали);

- По чек-листу, требуется реализовать:

  - Роуты `/login` и `/register`, `/forgot-password` и `/reset-password` недоступны авторизованным пользователям. Вот тут есть пример оптимального компонент `protect-route` <https://github.com/rdtabb/react-stellar-burger/pull/4#discussion_r1413010105> Вам не хватает проверки на `isAuthChecked`

Если у вас имеются какие-либо вопросы, то обращайтесь к наставнику;

2023-12-04 06:38 UTC, ArslanMustafin commented on src/components/burger-constructor/components/PriceOrder.tsx
> +        disabled={bun ? false : true}
**Можно лучше:**

тут достаточно просто оставить `disabled={bun}`

2023-12-08 18:31 UTC, rdtabb commented
Добрый вечер!

Хотел сделать пару замечаний:
 - У меня проект собирается правильно, ошибки не вылезают
 - Неавторизованные пользователи не имеют доступа к /login, /register и т.д. Не понимаю суть замечания. Вероятно поведение кода отличается на наших компьютерах
 
Спасибо за ревью!

2023-12-08 18:52 UTC, ArslanMustafin commented
> Добрый вечер!
> 
> Хотел сделать пару замечаний:
> 
> * У меня проект собирается правильно, ошибки не вылезают
> * Неавторизованные пользователи не имеют доступа к /login, /register и т.д. Не понимаю суть замечания. Вероятно поведение кода отличается на наших компьютерах
> 
> Спасибо за ревью!

Добрый, 1) а вы склонили свой проект? 2) авторизированный пользователь вообще не должен попадать на этот роут)) у вас скорее всего не очень правильно отрабатывает компонент protect-route. Посмотрите внимательнее на пример кода который я кидал ранее.  https://github.com/rdtabb/react-stellar-burger/pull/4#discussion_r1413010105

2023-12-08 18:58 UTC, rdtabb commented
1. Не склонил, пропустил это, извините
2. Я имел ввиду авторизованные, простите. Авторизованные пользователи не имеют доступа к формам авторизации, регистрации и так далее. Вот тут задеплоена актуальная сборка проекта:

[](https://stellar-burg.netlify.app/)

Все работает как надо

2023-12-08 19:09 UTC, ArslanMustafin commented
> 1. Не склонил, пропустил это, извините
> 2. Я имел ввиду авторизованные, простите. Авторизованные пользователи не имеют доступа к формам авторизации, регистрации и так далее. Вот тут задеплоена актуальная сборка проекта:
> 
> https://stellar-burg.netlify.app/
> 
> Все работает как надо

я имел ввиду, то что когда авторизованный пользователь переходит на роут `/login` и т.п. его должно перенаправлять на главную страницу.

``js
  if (onlyUnAuth && user) {
    const { from } = location.state || { from: { pathname: "/" } };
    return <Navigate to={from} />;
  }

Вот этот кусок кода за это отвечает.
```

у вас это есть, тут всё окей.

```js
  if (onlyUnAuth && isAuth) {
    return <Navigate to={{ pathname: ROUTES.CONSTRUCTOR }} />;
  }
```

Но вам не хватает проверки на прохождение авторизации.

```js
  if (!isAuthChecked) {
    return <Preloader />; // тут может быть что угодно, пока не произошло получения данных, пользователь не увидит контент
  }
```

isAuthChecked - это просто флаг, который показывает, выполнился ли запрос на получения пользователя или ещё нет. Важен сам процесс, если он завершёisAuthChecked - это просто флаг, который показывает, выполнился ли запрос на получения пользователя или ещё нет. Важен сам процесс, если он завершён, то флаг будет true (не зависит от результат, т.к. он будет true в любом случае, даже если будет ошибка), если он ещё не произошёл, то будет false.н, то флаг будет true (не зависит от результат, т.к. он будет true в любом случае, даже если будет ошибка), если он ещё не произошёл, то будет false.

2023-12-08 19:13 UTC, rdtabb commented
> > 1. Не склонил, пропустил это, извините
> > 2. Я имел ввиду авторизованные, простите. Авторизованные пользователи не имеют доступа к формам авторизации, регистрации и так далее. Вот тут задеплоена актуальная сборка проекта:
> > 
> > https://stellar-burg.netlify.app/
> > Все работает как надо
> 
> я имел ввиду, то что когда авторизованный пользователь переходит на роут `/login` и т.п. его должно перенаправлять на главную страницу.
> 
> ```js
>   if (onlyUnAuth && user) {
>     const { from } = location.state || { from: { pathname: "/" } };
>     return <Navigate to={from} />;
>   }
> ```
> 
> Вот этот кусок кода за это отвечает.
> 
> у вас это есть, тут всё окей.
> 
> ```js
>   if (onlyUnAuth && isAuth) {
>     return <Navigate to={{ pathname: ROUTES.CONSTRUCTOR }} />;
>   }
> ```
> 
> Но вам не хватает проверки на прохождение авторизации.
> 
> ```js
>   if (!isAuthChecked) {
>     return <Preloader />; // тут может быть что угодно, пока не произошло получения данных, пользователь не увидит контент
>   }
> ```
> 
> isAuthChecked - это просто флаг, который показывает, выполнился ли запрос на получения пользователя или ещё нет. Важен сам процесс, если он завершёisAuthChecked - это просто флаг, который показывает, выполнился ли запрос на получения пользователя или ещё нет. Важен сам процесс, если он завершён, то флаг будет true (не зависит от результат, т.к. он будет true в любом случае, даже если будет ошибка), если он ещё не произошёл, то будет false.н, то флаг будет true (не зависит от результат, т.к. он будет true в любом случае, даже если будет ошибка), если он ещё не произошёл, то будет false.

То есть Preloader необходим, чтобы во время процесса авторизации показывался некий индикатор загрузки или что-то в этом роде?

2023-12-08 19:20 UTC, ArslanMustafin commented
> > > 1. Не склонил, пропустил это, извините
> > > 2. Я имел ввиду авторизованные, простите. Авторизованные пользователи не имеют доступа к формам авторизации, регистрации и так далее. Вот тут задеплоена актуальная сборка проекта:
> > > 
> > > https://stellar-burg.netlify.app/
> > > Все работает как надо
> > 
> > 
> > я имел ввиду, то что когда авторизованный пользователь переходит на роут `/login` и т.п. его должно перенаправлять на главную страницу.
> > ```js
> >   if (onlyUnAuth && user) {
> >     const { from } = location.state || { from: { pathname: "/" } };
> >     return <Navigate to={from} />;
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Вот этот кусок кода за это отвечает.
> > у вас это есть, тут всё окей.
> > ```js
> >   if (onlyUnAuth && isAuth) {
> >     return <Navigate to={{ pathname: ROUTES.CONSTRUCTOR }} />;
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Но вам не хватает проверки на прохождение авторизации.
> > ```js
> >   if (!isAuthChecked) {
> >     return <Preloader />; // тут может быть что угодно, пока не произошло получения данных, пользователь не увидит контент
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > isAuthChecked - это просто флаг, который показывает, выполнился ли запрос на получения пользователя или ещё нет. Важен сам процесс, если он завершёisAuthChecked - это просто флаг, который показывает, выполнился ли запрос на получения пользователя или ещё нет. Важен сам процесс, если он завершён, то флаг будет true (не зависит от результат, т.к. он будет true в любом случае, даже если будет ошибка), если он ещё не произошёл, то будет false.н, то флаг будет true (не зависит от результат, т.к. он будет true в любом случае, даже если будет ошибка), если он ещё не произошёл, то будет false.
> 
> То есть Preloader необходим, чтобы во время процесса авторизации показывался некий индикатор загрузки или что-то в этом роде?

Да) там даже просто `null` поставить можно, самое важное там проверка)

2023-12-08 19:23 UTC, rdtabb commented
> > > > 1. Не склонил, пропустил это, извините
> > > > 2. Я имел ввиду авторизованные, простите. Авторизованные пользователи не имеют доступа к формам авторизации, регистрации и так далее. Вот тут задеплоена актуальная сборка проекта:
> > > > 
> > > > https://stellar-burg.netlify.app/
> > > > Все работает как надо
> > > 
> > > 
> > > я имел ввиду, то что когда авторизованный пользователь переходит на роут `/login` и т.п. его должно перенаправлять на главную страницу.
> > > ```js
> > >   if (onlyUnAuth && user) {
> > >     const { from } = location.state || { from: { pathname: "/" } };
> > >     return <Navigate to={from} />;
> > >   }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Вот этот кусок кода за это отвечает.
> > > у вас это есть, тут всё окей.
> > > ```js
> > >   if (onlyUnAuth && isAuth) {
> > >     return <Navigate to={{ pathname: ROUTES.CONSTRUCTOR }} />;
> > >   }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Но вам не хватает проверки на прохождение авторизации.
> > > ```js
> > >   if (!isAuthChecked) {
> > >     return <Preloader />; // тут может быть что угодно, пока не произошло получения данных, пользователь не увидит контент
> > >   }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > isAuthChecked - это просто флаг, который показывает, выполнился ли запрос на получения пользователя или ещё нет. Важен сам процесс, если он завершёisAuthChecked - это просто флаг, который показывает, выполнился ли запрос на получения пользователя или ещё нет. Важен сам процесс, если он завершён, то флаг будет true (не зависит от результат, т.к. он будет true в любом случае, даже если будет ошибка), если он ещё не произошёл, то будет false.н, то флаг будет true (не зависит от результат, т.к. он будет true в любом случае, даже если будет ошибка), если он ещё не произошёл, то будет false.
> > 
> > 
> > То есть Preloader необходим, чтобы во время процесса авторизации показывался некий индикатор загрузки или что-то в этом роде?
> 
> Да) там даже просто `null` поставить можно, самое важное там проверка)

Понял, спасибо! сделаю завтра

2023-12-09 14:19 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

### **Вы молодец!**

- Практически все замечания были исправлены;

### **Но есть ещё несколько замечаний, которые нужно исправить:**

- <https://disk.yandex.com/i/MlA-lRJ2VD78dQ> - Проект не собирается, т.к. не совпадает регистр букв в названии файла и при импорте. Проверьте, что в системе контроля версий правильный регистр и при необходимости измените <https://noteskeeper.ru/heritage/672/>. Для проверки нужно клонировать проект, и переключиться на ветку PR;

- <https://disk.yandex.com/i/toYuYGSX6Not1Q> - если открыть страницу `ingredients/:id` в новом вкладке, то у вас не отображается нужный ингредиент, а отображается какой=то захардкоженный, такого быть не должно, если ингредиент не найден, то нужно перенаправлять пользователя на главную или сказать что данный ингредиент не найден.

- По чек-листу, требуется реализовать:

  - Роуты `/login` и `/register`, `/forgot-password` и `/reset-password` недоступны авторизованным пользователям. Вот тут есть пример оптимального компонент `protect-route` <https://github.com/rdtabb/react-stellar-burger/pull/4#discussion_r1413010105> Вам не хватает проверки на `isAuthChecked`

  - При попытке неавторизованных пользователей перейти на защищённые роуты происходит редирект на /login. После успешной авторизации происходит переадресация на тот маршрут, к которому пользователь не получил доступ ранее. За это отвечает компонент `protect-router`, а именно этот кусок кода (у вас уже есть что-то подобное, нужно лишь немного доработать редирект).

  ```js
  if (onlyUnAuth && isAuth) {
    // если пользователь ранее пытался перейти на защищённые роуты, то редирект,
    // после авторизации, будет к ним. Если нет, то на главную страницу приложения.
    const { from } = location.state || { from: { pathname: ROUTES.CONSTRUCTOR } };
    return <Navigate to={from} />;
  }
  ```

2023-12-09 14:19 UTC, ArslanMustafin commented on src/components/ingredient-details/use-selected-item.tsx
> +  return state?.item ?? defaultIngredient;
**Надо исправить:**

Это решение не работает, если пользователь зайдёт с новой вкладки.

вам нужно сделать поиск из полученных ингредиентов (у вас ведь записаны они в редаксе).
Используйте метод [find](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find).

2023-12-13 04:54 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

### **Осталось 1 замечание, которое нужно исправить:**

- <https://disk.yandex.com/i/I1f18VU6u22-Og> - если открыть страницу `ingredients/:id` `в новой вкладке`, то у вас не отображается ингредиент, если ингредиент не найден, то нужно перенаправлять пользователя на главную или сказать что данный ингредиент не найден.

2023-12-13 04:54 UTC, ArslanMustafin commented on src/components/Protected/Protected.tsx
> +  }
**Надо исправить:**

Эта проверка должна быть самая первая.

А проверка на `!onlyUnAuth` тут не нужна.
Также нужно добавить запрос на получение пользователя в компоненте `app`.

2023-12-13 04:54 UTC, ArslanMustafin commented on src/components/app-header/app-header.tsx
> +            onMouseOver={() => prefetchIngredients(CACHE_KEYS.INGREDIENTS)}
**Можно лучше:**

Не совсем понимаю зачем это нужно.

2023-12-13 04:54 UTC, ArslanMustafin commented on src/components/app/App.tsx
> +    dispatch(initAuthCheck());
**Надо исправить:**

Не стоит тут проверять токены, это избыточно.

Нужно добавить сюда запрос на получение пользователя `GET /auth/user`, а другой (в компоненте `src/components/profile-page-components/components/form.tsx`) нужно убрать. И именно в этом запросе нужно ставить флаг `isAuthChecked`. 

```js 
// без `useEffect` он тут не нужен, т.к. у вас RTQ query
useUserInfoQuery(CACHE_KEYS.USER_INFO);r

```

2023-12-13 21:41 UTC, rdtabb commented on src/components/app-header/app-header.tsx
> +            onMouseOver={() => prefetchIngredients(CACHE_KEYS.INGREDIENTS)}
чтобы пользователь при заходе на страницу конструктора видел данные сразу, без индикатора загрузки. Данные статические, в любом случае, лучше при первом ховере конструктора сложить их в кэш и потом оттуда тягать. По крайней мере мне так кажется

2023-12-14 07:08 UTC, ArslanMustafin commented on src/components/app-header/app-header.tsx
> +            onMouseOver={() => prefetchIngredients(CACHE_KEYS.INGREDIENTS)}
Понял, вот ещё неплохое решение:  Пользователь будет видеть данные сразу, если запрос сделать в `app`)) Это оптимальное решение, т.к. запрос будет происходить только 1 раз. И эти данные будут нужны практически на всех страницах)))

2023-12-14 07:13 UTC, ArslanMustafin commented on src/components/ingredient-details/ingredient-details.tsx
>    const selectedItem = useSelectedItem();
**Надо исправить:**

Я ведь говорил в общем комментарии, что у вас не находиться ингредиент, если открыть в новой вкладке `/ingredients/:id`. Для того чтобы найти нужный ингредиент, вам нужно получить его id из `url`. Сделать запрос на получение всех ингредиентов, а после найти этот ингредиент по `id`. Запрос на получение всех ингредиентов нужно делать в компоненте `app`.

2023-12-14 07:13 UTC, ArslanMustafin commented on src/components/app-header/app-header.tsx
> +            onMouseOver={() => prefetchIngredients(CACHE_KEYS.INGREDIENTS)}
Тем более вам этот запрос нужен для того чтобы находить ингредиент по `id`. Если пользователь открыл страницу `ingredients/:id` в новой вкладке.

2023-12-14 07:15 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

### **Работа принята, удачи в дальнейшем обучении! 🔥:**

2023-12-14 10:26 UTC, merged